/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 -t public/pawn.gltf
*/

import React from 'react'
import type { FC } from 'react'

import { useGLTF } from '@react-three/drei'
import { motion } from 'framer-motion-3d'
import type * as THREE from 'three'
import type { GLTF } from 'three-stdlib'

import type { ModelProps } from '.'
import { transitions, variants, PieceMaterial } from '.'

type GLTFResult = GLTF & {
  nodes: {
    Object001: THREE.Mesh
  }
  materials: {
    [`Object001_mtl.003`]: THREE.MeshStandardMaterial
  }
}

export const PawnModel: FC<ModelProps> = ({
  movingTo,
  handleMove,
  tileHeight,
  ...props
}) => {
  const { nodes } = useGLTF(`/pawn.gltf`) as unknown as GLTFResult
  return (
    <group {...props} dispose={null} castShadow>
      <motion.mesh
        geometry={nodes.Object001.geometry}
        scale={0.03}
        castShadow
        receiveShadow
        initial={false}
        animate={
          movingTo
            ? variants.move({ movingTo, tileHeight, ...props })
            : variants.select(props)
        }
        transition={movingTo ? transitions.moveTo : transitions.select}
        onAnimationComplete={() => {
          if (movingTo) {
            handleMove()
          }
        }}
      >
        <PieceMaterial color={props.color} isSelected={props.isSelected} />
      </motion.mesh>
    </group>
  )
}

useGLTF.preload(`/pawn.gltf`)
